import { defaultUrlTransform } from "react-markdown";
import React from 'react';
import { AlertTriangle, Info } from 'lucide-react';

export const extractTextFromReactNode = (node: any): string => {
    if (typeof node === 'string' || typeof node === 'number') {
        return String(node);
    }
    if (Array.isArray(node)) {
        return node.map(extractTextFromReactNode).join('');
    }
    if (React.isValidElement(node) && node.props && (node.props as any).children) {
        return extractTextFromReactNode((node.props as any).children);
    }
    return '';
};

// Hàm tự động chuẩn hóa văn bản Markdown, đặc biệt là bảng biểu thiếu dòng Header

/**
 * Ảnh nhúng thẳng dạng data: được phép hiển thị.
 *
 * react-markdown chỉ cho qua https, http, irc, mailto, xmpp - gặp "data:image/jpeg;base64,..."
 * là XOÁ TRẮNG thuộc tính src, thẻ ảnh vẫn dựng ra nhưng rỗng nên hiện thành ảnh vỡ.
 * Đo trên kho Toán: 219 câu chèn ảnh kiểu này (do dán thẳng từ Word hoặc chụp màn hình)
 * đều mất ảnh ở mọi màn hình - kể cả bài luyện tập phía học sinh.
 *
 * CỐ Ý không cho qua svg+xml: tệp SVG chứa được mã chạy, mà ảnh minh hoạ toán lý chỉ
 * cần ảnh thường. Mọi thứ khác vẫn để react-markdown lọc như cũ.
 */
const ANH_NHUNG_AN_TOAN = /^data:image\/(png|jpe?g|gif|webp|bmp|avif)[;,]/i;

export const chuyenDiaChiAnh = (url: string): string => {
  if (ANH_NHUNG_AN_TOAN.test(String(url || ''))) return url;
  return defaultUrlTransform(url);
};

export const preprocessMarkdown = (text: string): string => {
    if (typeof text !== 'string') return text;
    
    // Fix JSON parse escaping errors commonly generated by AI
    let s = text;
    s = s.replace(/\x0Crac/g, '\\frac');
    s = s.replace(/\x0Bec/g, '\\vec');
    s = s.replace(/\x0Aeq/g, '\\neq');
    s = s.replace(/\x08eta/g, '\\beta');
    s = s.replace(/\x08egin/g, '\\begin');
    s = s.replace(/\x09an/g, '\\tan');
    s = s.replace(/\x09heta/g, '\\theta');
    s = s.replace(/\x0Dightarrow/g, '\\rightarrow');
    s = s.replace(/\x0Dight/g, '\\right');
    text = s;

    if (typeof text !== 'string') return text;
    const lines = text.split('\n');
    for (let i = 0; i < lines.length; i++) {
        const line = lines[i].trim();
        const isDelimiterRow = /^\|?[\s:\-]+\|[\s:\-|]*$/.test(line) && line.includes('-');
        if (isDelimiterRow) {
            const prevLine = i > 0 ? lines[i-1].trim() : '';
            const isPrevRowTable = prevLine.includes('|');
            if (!isPrevRowTable) {
                const cols = line.split('|').filter(c => c.trim().length > 0).length;
                let emptyHeader = '|';
                for(let c = 0; c < cols; c++) emptyHeader += ' &nbsp; |';
                lines.splice(i, 0, emptyHeader);
                i++;
            }
        }
    }
    return lines.join('\n');
};

/**
 * Cỡ ảnh - đọc từ TIÊU ĐỀ ảnh của Markdown chuẩn: `![Hình ảnh](url "nho|vua|to")`.
 *
 * Dùng tiêu đề chứ không bịa cú pháp riêng: `title` là thứ Markdown vốn có, nên chỗ nào
 * chưa hiểu quy ước này thì ảnh vẫn hiện bình thường, không vỡ gì.
 *
 * Vì sao cần: đo 14 ảnh thật đang dùng trong kho thì nhỏ nhất 211x228px, lớn nhất
 * 3124x1376px - chênh 15 lần bề rộng. Trước đây KHÔNG có quy tắc nào cho thẻ ảnh nên ảnh
 * to nhỏ tuỳ file: ảnh 211px hiện bé đến mức không đọc nổi vạch chia của đồ thị, còn ảnh
 * 3124px thì tràn cả khung.
 */
const CO_ANH: Record<string, string> = {
  nho: 'max-h-[180px]',
  vua: 'max-h-[320px]',
  to: 'max-h-[520px]',
};

/** Lớp CSS cho một thẻ ảnh trong nội dung bài. `title` là cỡ Thầy cô chọn (nếu có). */
export const docCoTuTitle = (title?: string): 'nho' | 'vua' | 'to' => {
  const t = String(title || '').trim().toLowerCase();
  return (t === 'nho' || t === 'to') ? t : 'vua';
};

export const lopAnhNoiDung = (title?: string): string => {
  const co = CO_ANH[String(title || '').trim().toLowerCase()] || CO_ANH.vua;
  // min-w: ảnh bé quá thì phóng lên cho đọc được, nhưng chỉ ở màn rộng - điện thoại mà ép
  // rộng 240px thì ảnh lại tràn ra ngoài.
  // .anh-noi-dung: dấu để globals.css bỏ qua, khỏi bị luật !important của nó đè cỡ ảnh
  return `anh-noi-dung ${co} w-auto max-w-full sm:min-w-[240px] object-contain rounded-lg border border-slate-200 bg-white`;
};

/**
 * Đoạn văn chỉ chứa toàn ảnh thì xếp NGANG.
 *
 * Markdown gộp các dòng liền nhau vào một đoạn, nên hai dòng ảnh sát nhau (không có dòng
 * trống ở giữa) sẽ nằm chung một đoạn -> xếp ngang. Cách nhau một dòng trống thì thành hai
 * đoạn riêng -> xếp dọc như cũ. Không phải học cú pháp mới.
 *
 * Dự án có bật remarkBreaks nên giữa hai ảnh còn có thẻ xuống dòng - phải bỏ qua nó, nếu
 * không thì không đoạn nào được coi là "chỉ toàn ảnh".
 */
export const demAnhTrongDoan = (children: any): number => {
  const ds = React.Children.toArray(children);
  let soAnh = 0;
  for (const c of ds) {
    if (typeof c === 'string') {
      if (c.trim()) return 0;   // còn chữ thì không phải đoạn ảnh
      continue;
    }
    // Nhận ra ảnh bằng thuộc tính src, KHÔNG dựa vào tên thẻ: thẻ img đã bị thay bằng
    // thành phần riêng nên `type` là hàm của mình chứ không còn là chuỗi 'img'.
    const props = (c as any)?.props || {};
    if (props.src) { soAnh++; continue; }
    const the = (c as any)?.type;
    const ten = typeof the === 'string' ? the : (the?.name || '');
    if (ten === 'br') continue;  // remarkBreaks chèn vào giữa hai dòng ảnh
    return 0;
  }
  return soAnh;
};

const sanitizeStyle = (style: any) => {
    let parsedStyle: any = {};
    if (typeof style === 'string') {
        style.split(';').forEach((rule: string) => {
            const [key, val] = rule.split(':');
            if (key && val) {
                const camelKey = key.trim().replace(/-([a-z])/g, (g: any) => g[1].toUpperCase());
                parsedStyle[camelKey] = val.trim();
            }
        });
    } else if (style) {
        parsedStyle = { ...style };
    }
    return parsedStyle;
};

const stripTriggerPrefix = (children: any): any => {
    let contentFound = false;
    const triggerRegex = /^[\s]*(ví dụ|vd|phương pháp|pp|lời giải chi tiết|lời giải|hướng dẫn giải|hướng dẫn|hdg|hd|chú ý|lưu ý|định lý|định nghĩa|tổng quát|lý thuyết)[\s]*[:.-]?[\s]*/i;
    
    const walk = (node: any): any => {
        if (contentFound) return node;

        if (typeof node === 'string') {
            if (!contentFound) {
                const original = node;
                let replaced = original.replace(triggerRegex, '');
                
                if (replaced === original && original.match(/^[\s]*[:.-]?[\s]*$/)) {
                    return '';
                } else if (replaced === original) {
                    if (original.trim().length > 0) {
                        replaced = original.replace(/^[\s]*[:.-]?[\s]*/, '');
                        if (replaced.trim().length > 0) contentFound = true;
                        return replaced;
                    }
                } else {
                    if (replaced.trim().length > 0) contentFound = true;
                    return replaced;
                }
            }
            return node;
        }

        if (Array.isArray(node)) {
            return node.map(walk);
        }

        if (React.isValidElement(node)) {
            const props: any = { ...(node.props || {}) };
            if (props.children) {
                props.children = walk(props.children);
            }
            return React.cloneElement(node, props);
        }

        return node;
    };

    return walk(children);
};

export const unifiedMarkdownComponents: any = {
   div: ({node, style, children, ...props}: any) => {
       return <div style={sanitizeStyle(style)} {...props}>{children}</div>;
   },
   span: ({node, style, children, ...props}: any) => {
       return <span style={sanitizeStyle(style)} {...props}>{children}</span>;
   },
   h1: ({node, style, children, ...props}: any) => {
       return (
           /* Tiêu đề bài CANH GIỮA - đây là dòng mở đầu cả bài, đặt lệch trái nhìn như
              một mục con. Thanh xanh chuyển xuống thành gạch chân cho cân. */
           <div className="not-prose mt-12 mb-7 w-full text-center">
               <h1 style={sanitizeStyle(style)} className="text-[55px] font-black text-blue-900 tracking-tight m-0 leading-tight" {...props}>{children}</h1>
               <div className="mx-auto mt-3 h-[6px] w-24 bg-blue-600 rounded-full"></div>
           </div>
       );
   },
   h2: ({node, style, children, ...props}: any) => {
       return (
           <div className="not-prose mt-10 mb-6 flex justify-center w-full">
               <div className="bg-red-50 text-red-700 px-6 py-3 rounded-r-3xl rounded-l-lg border-l-[8px] border-red-600 font-bold shadow-sm inline-block w-fit leading-relaxed max-w-[95%] break-words text-[45px] uppercase text-center" style={sanitizeStyle(style)} {...props}>
                   {children}
               </div>
           </div>
       );
   },
   h3: ({node, style, children, ...props}: any) => {
       return (
           <h3 style={sanitizeStyle(style)} className="not-prose mt-8 mb-5 text-[40px] font-bold text-indigo-900 tracking-tight leading-[1.35] pl-5 py-2 border-l-[8px] border-indigo-500 bg-indigo-50/50 rounded-r-xl shadow-sm" {...props}>
               {children}
           </h3>
       );
   },
   h4: ({node, style, children, ...props}: any) => {
       return (
           /* Mục con a) b) c) - BỎ dấu ❖ theo yêu cầu, giữ nguyên màu và gạch chân. */
           <h4 style={sanitizeStyle(style)} className="not-prose mt-6 mb-3 ml-5 text-[36px] font-bold text-teal-800 tracking-tight" {...props}>
               <span className="inline-block border-b-2 border-teal-100 pb-1.5">{children}</span>
           </h4>
       );
   },
   h5: ({node, style, children, ...props}: any) => {
       return (
           /* ##### của bài cũ: nay hiện y như Ý lớn (chữ thường, gạch "–") để bài cũ và
              bài mới nhìn cùng một kiểu. Đo được chỉ 33 dòng trong 6 mục nên đổi an toàn. */
           <h5 style={sanitizeStyle(style)} className="not-prose mt-3 mb-2 ml-8 text-[35px] font-normal text-slate-700 leading-[1.55] flex items-start gap-3" {...props}>
               <span className="shrink-0 font-bold text-slate-500">–</span>
               <span className="flex-1 min-w-0">{children}</span>
           </h5>
       );
   },
   strong: ({node, style, children, ...props}: any) => {
       return <strong style={sanitizeStyle(style)} {...props} className="text-slate-900 font-bold">{children}</strong>;
   },
   /* Ba bậc ý dùng chung lớp .ds-y (globals.css): dấu "–", "+", "•" và độ thụt lề đo
      bằng em nên tự co theo cỡ chữ của từng nơi. */
   ul: ({node, style, children, ...props}: any) => (
       <ul style={sanitizeStyle(style)} className="ds-y not-prose mb-4 space-y-1.5" {...props}>{children}</ul>
   ),
   li: ({node, style, children, ...props}: any) => {
       return (
           <li style={sanitizeStyle(style)} className="mb-2 text-[35px] leading-[1.55] text-slate-700" {...props}>
              {children}
           </li>
       );
   },
   img: ({node, src, alt, title, ...props}: any) => (
       // data-co: để nơi khác (VD ô sửa tại chỗ) thu nhỏ ảnh theo tỉ lệ mà vẫn phân biệt
       // được ba cỡ; nếu đè cứng một chiều cao thì bấm Nhỏ/Vừa/To đều như nhau.
       <img src={src} alt={alt || 'Hình ảnh'} title={title} loading="lazy" data-co={docCoTuTitle(title)}
            className={`inline-block my-2 ${lopAnhNoiDung(title)}`} {...props} />
   ),
   p: ({node, style, children, ...props}: any) => {
       // Đoạn chỉ toàn ảnh (hai dòng ảnh sát nhau) thì xếp ngang cho dễ đối chiếu
       const soAnh = demAnhTrongDoan(children);
       if (soAnh > 1) {
           return (
               <div style={sanitizeStyle(style)} className="mb-6 flex flex-wrap items-start justify-center gap-4">
                   {children}
               </div>
           );
       }
       return <p style={sanitizeStyle(style)} className="mb-6 text-[35px] leading-[1.6] text-slate-800" {...props}>{children}</p>;
   },
   blockquote: ({node, style, children, ...props}: any) => {
       const text = extractTextFromReactNode(children).trim();
       const lowerText = text.toLowerCase().replace(/[:.,-]/g, '').trim();
       
       let type = 'default';
       let icon = <Info className="w-5 h-5" />;
       let bgClass = 'bg-gray-50';
       let borderClass = 'border-gray-400';
       let headerClass = 'bg-gray-200/50 text-gray-800 border-gray-300';
       let headerText = 'NỘI DUNG';

       if (lowerText.startsWith('ví dụ') || lowerText.startsWith('vd')) {
           type = 'example';
           icon = <span className="text-lg leading-none">📌</span>;
           bgClass = 'bg-emerald-50'; borderClass = 'border-emerald-500'; headerClass = 'bg-emerald-100/70 text-emerald-900 border-emerald-200';
           headerText = 'VÍ DỤ';
       } else if (lowerText.startsWith('phương pháp') || lowerText.startsWith('pp')) {
           type = 'method';
           icon = <span className="text-lg leading-none">💡</span>;
           bgClass = 'bg-amber-50'; borderClass = 'border-amber-500'; headerClass = 'bg-amber-100/70 text-amber-900 border-amber-200';
           headerText = 'PHƯƠNG PHÁP';
       } else if (lowerText.startsWith('lời giải') || lowerText.startsWith('hướng dẫn') || lowerText.startsWith('hd') || lowerText.startsWith('hdg')) {
           type = 'solution';
           icon = <span className="text-lg leading-none">🎯</span>;
           bgClass = 'bg-indigo-50'; borderClass = 'border-indigo-500'; headerClass = 'bg-indigo-100/70 text-indigo-900 border-indigo-200';
           headerText = 'HƯỚNG DẪN GIẢI';
       } else if (lowerText.startsWith('chú ý') || lowerText.startsWith('lưu ý')) {
           type = 'note';
           icon = <AlertTriangle className="w-5 h-5 text-red-600" />;
           bgClass = 'bg-red-50'; borderClass = 'border-red-500'; headerClass = 'bg-red-100/70 text-red-900 border-red-200';
           headerText = 'CHÚ Ý';
       } else if (lowerText.startsWith('định lý') || lowerText.startsWith('định nghĩa') || lowerText.startsWith('tổng quát') || lowerText.startsWith('lý thuyết')) {
           type = 'theorem';
           icon = <span className="text-lg leading-none">📖</span>;
           bgClass = 'bg-blue-50'; borderClass = 'border-blue-500'; headerClass = 'bg-blue-100/70 text-blue-900 border-blue-200';
           headerText = 'KIẾN THỨC TRỌNG TÂM';
       }

       if (type !== 'default') {
           const processedChildren = stripTriggerPrefix(children);
           return (
               <div className={`not-prose my-6 rounded-xl border-2 ${borderClass} ${bgClass} shadow-sm overflow-hidden flex flex-col`}>
                   <div className={`px-4 py-2 border-b ${headerClass} font-bold flex items-center gap-2 uppercase tracking-wide text-[35px]`}>
                       {icon} <span>{headerText}</span>
                   </div>
                   <div className="hop-giai px-5 py-4 flex-1 min-w-0 prose prose-slate max-w-none text-slate-800 leading-[1.55] font-medium text-[35px]">
                       {processedChildren}
                   </div>
               </div>
           );
       }

       return (
           <blockquote className="not-prose my-6 border-l-[6px] border-slate-400 bg-slate-50 px-6 py-5 rounded-r-xl italic text-slate-700 shadow-sm text-[35px]" {...props}>
               <div className="prose prose-slate max-w-none text-inherit [&>p:first-child]:mt-0 [&>p:last-child]:mb-0 text-[35px]">{children}</div>
           </blockquote>
       );
    },
    table: ({node, style, children, ...props}: any) => (
        <div className="overflow-x-auto my-6 not-prose">
            <table className="w-full text-left border-collapse border-2 border-slate-400 text-[28px]" style={sanitizeStyle(style)} {...props}>
                {children}
            </table>
        </div>
    ),
    thead: ({node, style, children, ...props}: any) => (
        <thead className="bg-slate-100 font-bold" style={sanitizeStyle(style)} {...props}>
            {children}
        </thead>
    ),
    tbody: ({node, style, children, ...props}: any) => (
        <tbody className="bg-white" style={sanitizeStyle(style)} {...props}>
            {children}
        </tbody>
    ),
    tr: ({node, style, children, ...props}: any) => (
        <tr className="hover:bg-slate-50 transition-colors" style={sanitizeStyle(style)} {...props}>
            {children}
        </tr>
    ),
    th: ({node, style, children, ...props}: any) => (
        <th className="px-5 py-3 border-2 border-slate-400 text-slate-800 font-bold" style={sanitizeStyle(style)} {...props}>
            {children}
        </th>
    ),
    td: ({node, style, children, ...props}: any) => (
        <td className="px-5 py-3 border-2 border-slate-400 text-slate-700 align-top" style={sanitizeStyle(style)} {...props}>
            {children}
        </td>
    )
};

export const appMarkdownComponents = unifiedMarkdownComponents;
export const customMarkdownComponents = unifiedMarkdownComponents;

export const studentMarkdownComponents: any = {
   div: ({node, style, children, ...props}: any) => {
       return <div style={sanitizeStyle(style)} {...props}>{children}</div>;
   },
   span: ({node, style, children, ...props}: any) => {
       return <span style={sanitizeStyle(style)} {...props}>{children}</span>;
   },
   h1: ({node, style, children, ...props}: any) => {
       return (
           /* Tiêu đề bài CANH GIỮA - xem chú thích ở bộ unified. */
           <div className="not-prose mt-6 mb-5 w-full text-center">
               <h1 style={sanitizeStyle(style)} className="text-2xl sm:text-3xl font-black text-blue-900 tracking-tight m-0 leading-tight" {...props}>{children}</h1>
               <div className="mx-auto mt-2 h-1 w-16 bg-blue-600 rounded-full"></div>
           </div>
       );
   },
   h2: ({node, style, children, ...props}: any) => {
       return (
           <div className="not-prose mt-6 mb-4 flex justify-center w-full">
               <div className="bg-red-50 text-red-700 px-4 py-2 rounded-r-2xl rounded-l-md border-l-[6px] border-red-600 font-bold shadow-sm inline-block w-fit leading-relaxed max-w-[95%] break-words text-xl sm:text-2xl uppercase text-center" style={sanitizeStyle(style)} {...props}>
                   {children}
               </div>
           </div>
       );
   },
   h3: ({node, style, children, ...props}: any) => {
       return (
           <h3 style={sanitizeStyle(style)} className="not-prose mt-6 mb-4 text-xl sm:text-2xl font-bold text-indigo-900 tracking-tight leading-[1.35] pl-4 py-1.5 border-l-[6px] border-indigo-500 bg-indigo-50/50 rounded-r-lg shadow-sm" {...props}>
               {children}
           </h3>
       );
   },
   h4: ({node, style, children, ...props}: any) => {
       return (
           /* Mục con a) b) c) - bỏ dấu ❖. */
           <h4 style={sanitizeStyle(style)} className="not-prose mt-5 mb-2 ml-2 sm:ml-3 text-lg sm:text-xl font-bold text-teal-800 tracking-tight" {...props}>
               <span className="inline-block border-b-2 border-teal-100 pb-1">{children}</span>
           </h4>
       );
   },
   h5: ({node, style, children, ...props}: any) => {
       return (
           /* ##### của bài cũ: hiện như Ý lớn. */
           <h5 style={sanitizeStyle(style)} className="not-prose mt-2 mb-1.5 ml-4 sm:ml-5 text-base sm:text-lg font-normal text-slate-700 leading-[1.55] flex items-start gap-2" {...props}>
               <span className="shrink-0 font-bold text-slate-500">–</span>
               <span className="flex-1 min-w-0">{children}</span>
           </h5>
       );
   },
   strong: ({node, style, children, ...props}: any) => {
       return <strong style={sanitizeStyle(style)} {...props} className="text-slate-900 font-bold">{children}</strong>;
   },
   table: ({node, style, children, ...props}: any) => (
       <div className="overflow-x-auto my-6 not-prose">
           <table className="w-full text-left border-collapse border border-slate-400 text-sm md:text-base" style={sanitizeStyle(style)} {...props}>
               {children}
           </table>
       </div>
   ),
   thead: ({node, style, children, ...props}: any) => (
       <thead className="bg-slate-100 font-bold" style={sanitizeStyle(style)} {...props}>
           {children}
       </thead>
   ),
   tbody: ({node, style, children, ...props}: any) => (
       <tbody className="bg-white" style={sanitizeStyle(style)} {...props}>
           {children}
       </tbody>
   ),
   tr: ({node, style, children, ...props}: any) => (
       <tr className="hover:bg-slate-50 transition-colors" style={sanitizeStyle(style)} {...props}>
           {children}
       </tr>
   ),
   th: ({node, style, children, ...props}: any) => (
       <th className="px-4 py-2 border border-slate-400 text-slate-800 font-bold" style={sanitizeStyle(style)} {...props}>
           {children}
       </th>
   ),
   td: ({node, style, children, ...props}: any) => (
       <td className="px-4 py-2 border border-slate-400 text-slate-700 align-top" style={sanitizeStyle(style)} {...props}>
           {children}
       </td>
   ),
   /* Ba bậc ý dùng chung lớp .ds-y - xem globals.css. */
   ul: ({node, style, children, ...props}: any) => (
       <ul style={sanitizeStyle(style)} className="ds-y not-prose mb-3 space-y-1" {...props}>{children}</ul>
   ),
   li: ({node, style, children, ...props}: any) => {
       return (
           <li style={sanitizeStyle(style)} className="mb-1.5 leading-[1.6] text-slate-700" {...props}>
              {children}
           </li>
       );
   },
   img: ({node, src, alt, title, ...props}: any) => (
       // data-co: để nơi khác (VD ô sửa tại chỗ) thu nhỏ ảnh theo tỉ lệ mà vẫn phân biệt
       // được ba cỡ; nếu đè cứng một chiều cao thì bấm Nhỏ/Vừa/To đều như nhau.
       <img src={src} alt={alt || 'Hình ảnh'} title={title} loading="lazy" data-co={docCoTuTitle(title)}
            className={`inline-block my-2 ${lopAnhNoiDung(title)}`} {...props} />
   ),
   p: ({node, style, children, ...props}: any) => {
       const soAnh = demAnhTrongDoan(children);
       if (soAnh > 1) {
           return (
               <div style={sanitizeStyle(style)} className="mb-3 flex flex-wrap items-start justify-center gap-3">
                   {children}
               </div>
           );
       }
       return <p style={sanitizeStyle(style)} className="mb-3 leading-[1.6] text-slate-800" {...props}>{children}</p>;
   },
   blockquote: ({node, style, children, ...props}: any) => {
       const text = extractTextFromReactNode(children).trim();
       const lowerText = text.toLowerCase().replace(/[:.,-]/g, '').trim();
       
       let type = 'default';
       let icon = <Info className="w-4 h-4" />;
       let bgClass = 'bg-gray-50';
       let borderClass = 'border-gray-400';
       let headerClass = 'bg-gray-200/50 text-gray-800 border-gray-300';
       let headerText = 'NỘI DUNG';

       if (lowerText.startsWith('ví dụ') || lowerText.startsWith('vd')) {
           type = 'example';
           icon = <span className="text-base leading-none">📌</span>;
           bgClass = 'bg-emerald-50'; borderClass = 'border-emerald-500'; headerClass = 'bg-emerald-100/70 text-emerald-900 border-emerald-200';
           headerText = 'VÍ DỤ';
       } else if (lowerText.startsWith('phương pháp') || lowerText.startsWith('pp')) {
           type = 'method';
           icon = <span className="text-base leading-none">💡</span>;
           bgClass = 'bg-amber-50'; borderClass = 'border-amber-500'; headerClass = 'bg-amber-100/70 text-amber-900 border-amber-200';
           headerText = 'PHƯƠNG PHÁP';
       } else if (lowerText.startsWith('lời giải') || lowerText.startsWith('hướng dẫn') || lowerText.startsWith('hd') || lowerText.startsWith('hdg')) {
           type = 'solution';
           icon = <span className="text-base leading-none">🎯</span>;
           bgClass = 'bg-indigo-50'; borderClass = 'border-indigo-500'; headerClass = 'bg-indigo-100/70 text-indigo-900 border-indigo-200';
           headerText = 'HƯỚNG DẪN GIẢI';
       } else if (lowerText.startsWith('chú ý') || lowerText.startsWith('lưu ý')) {
           type = 'note';
           icon = <AlertTriangle className="w-4 h-4 text-red-600" />;
           bgClass = 'bg-red-50'; borderClass = 'border-red-500'; headerClass = 'bg-red-100/70 text-red-900 border-red-200';
           headerText = 'CHÚ Ý';
       } else if (lowerText.startsWith('định lý') || lowerText.startsWith('định nghĩa') || lowerText.startsWith('tổng quát') || lowerText.startsWith('lý thuyết')) {
           type = 'theorem';
           icon = <span className="text-base leading-none">📖</span>;
           bgClass = 'bg-blue-50'; borderClass = 'border-blue-500'; headerClass = 'bg-blue-100/70 text-blue-900 border-blue-200';
           headerText = 'KIẾN THỨC TRỌNG TÂM';
       }

       if (type !== 'default') {
           const processedChildren = stripTriggerPrefix(children);
           return (
               <div className={`not-prose my-4 rounded-xl border-2 ${borderClass} ${bgClass} shadow-sm overflow-hidden flex flex-col`}>
                   <div className={`px-3 py-1.5 border-b ${headerClass} font-bold flex items-center gap-2 uppercase tracking-wide text-sm`}>
                       {icon} <span>{headerText}</span>
                   </div>
                   <div className="hop-giai px-4 py-3 flex-1 min-w-0 prose prose-slate prose-sm sm:prose-base max-w-none text-slate-800 leading-[1.55] font-medium">
                       {processedChildren}
                   </div>
               </div>
           );
       }

       return (
           <blockquote className="not-prose my-4 border-l-[4px] border-slate-400 bg-slate-50 px-4 py-3 rounded-r-xl italic text-slate-700 shadow-sm" {...props}>
               <div className="prose prose-slate prose-sm sm:prose-base max-w-none text-inherit [&>p:first-child]:mt-0 [&>p:last-child]:mb-0">{children}</div>
           </blockquote>
       );
   }
};

export const checkAndRenderSpecialBlock = () => null;
