export function fixLatexText(text: string): string {
    let fixed = text;
    fixed = fixed.replace(/\[cite_start\]/g, "").replace(/\[cite_end\]/g, "");
    fixed = fixed.replace(/\{\{\s*begincases\s*\}\}/g, "\\begin{cases}");
    fixed = fixed.replace(/\{\{\s*endcases\s*\}\}/g, "\\end{cases}");
    fixed = fixed.replace(/\\rightarrow/g, "\\rightarrow ");
    
    // Sửa lỗi ngắt dòng cho TẤT CẢ các hệ phương trình:
    // AI thường sinh ra 2 dấu gạch chéo (\\) nhưng Markdown cần 4 dấu (\\\\) để xuống dòng trong KaTeX
    fixed = fixed.replace(/\\begin\{cases\}([\s\S]*?)\\end\{cases\}/g, (match, inner) => {
        // Tìm chữ "\\" (được biểu diễn là "\\\\" trong chuỗi JS) mà chưa phải là 4 dấu, đổi thành "\\\\\\\\"
        let fixedInner = inner.replace(/(?<!\\)\\\\(?!\\)/g, "\\\\\\\\");
        return `\\begin{cases}${fixedInner}\\end{cases}`;
    });

    // Tự động bọc dấu $$ (block math) cho hệ phương trình nếu AI quên bọc
    // Block math giúp công thức xuống dòng độc lập và hiển thị to rõ hơn
    fixed = fixed.replace(/(?<!\$)\\begin\{cases\}[\s\S]*?\\end\{cases\}(?!\$)/g, "$$$$$&$$$$");
    
    return fixed;
}

export function applyLatexFixToActiveElement(): boolean {
    if (typeof document === 'undefined') return false;
    
    const activeEl = document.activeElement as HTMLTextAreaElement | HTMLInputElement;
    if (!activeEl || (activeEl.tagName !== 'TEXTAREA' && activeEl.tagName !== 'INPUT')) {
        return false;
    }

    const start = activeEl.selectionStart;
    const end = activeEl.selectionEnd;

    // Nếu không có vùng chọn (bôi đen), trả về false để áp dụng sửa đổi toàn bộ
    if (start === null || end === null || start === end) {
        return false;
    }

    const val = activeEl.value;
    const selected = val.substring(start, end);

    const fixedSelected = fixLatexText(selected);

    // Thay thế text trong vùng bôi đen
    activeEl.setRangeText(fixedSelected, start, end, 'select');

    // Kích hoạt sự kiện onInput để React (thông qua onChange) nhận diện thay đổi state
    const event = new Event('input', { bubbles: true });
    activeEl.dispatchEvent(event);
    
    return true; // Đã xử lý bôi đen thành công
}

/**
 * Các lệnh LaTeX bắt đầu bằng chữ "n" - phần đuôi sau "\n".
 * Xếp dài trước ngắn để "\neq" không bị khớp nhầm thành "\ne" + "q".
 */
const DUOI_LENH_N = [
    'leftrightarrow', 'rightarrow', 'leftarrow', 'subseteq', 'supseteq',
    'earrow', 'warrow', 'atural', 'parallel', 'exists', 'equiv',
    'subset', 'supset', 'vdash', 'otin', 'abla', 'cong', 'less',
    'geq', 'leq', 'gtr', 'mid', 'sim', 'eq', 'eg', 'ot', 'u', 'i', 'e',
];
const RE_XUONG_DONG = new RegExp(`\\\\n(?!(?:${DUOI_LENH_N.join('|')})\\b)`, 'g');
const RE_KHOI_PHUC_N = new RegExp(`\\x0A(${DUOI_LENH_N.join('|')})\\b`, 'g');

/**
 * Đổi "\n" (hai ký tự) thành dấu xuống dòng, NHƯNG chỉ ở phần nằm NGOÀI công thức.
 *
 * Đây là cách phân biệt đáng tin nhất giữa hai thứ trông giống hệt nhau:
 *   - Ngoài công thức: "\nVậy ta có..." là xuống dòng rồi tới chữ "Vậy".
 *   - Trong công thức: "$x \ne 0$" là lệnh KHÁC 0, không được cắt.
 *
 * Bản cũ chỉ dựa vào một danh sách lệnh cần chừa, mà danh sách đó thiếu "\ne" -
 * lệnh rất hay dùng khi viết điều kiện xác định. Hậu quả: "$x \ne 0$" bị cắt thành
 * xuống dòng + "e 0", kéo theo cả \begin{cases} bao quanh cũng vỡ theo.
 * Danh sách vẫn giữ để phòng khi công thức bị thiếu dấu $ bao ngoài.
 */
function doiXuongDongNgoaiCongThuc(s: string): string {
    // Tách xen kẽ: [ngoài] $công thức$ [ngoài] $$công thức$$ [ngoài]...
    const phan = s.split(/(\$\$[\s\S]*?\$\$|\$[^$\n]*?\$)/);
    return phan
        .map((p) => (p.startsWith('$') && p.length > 1 ? p : p.replace(RE_XUONG_DONG, '\n')))
        .join('');
}

export function cleanLatexControlChars(s: string): string {
    if (!s || typeof s !== 'string') return s;
    let res = s;
    res = doiXuongDongNgoaiCongThuc(res);

    // Nếu có mã điều khiển 0x0A (Line Feed) + lệnh thì fix lại thành backslash + lệnh
    res = res.replace(RE_KHOI_PHUC_N, '\\n$1');
    // Fix JSON parse escaping errors commonly generated by AI
    res = res.replace(/\x0Crac/g, '\\frac');
    res = res.replace(/\x0Corall/g, '\\forall');
    res = res.replace(/\x0Bec/g, '\\vec');
    res = res.replace(/\x08eta/g, '\\beta');
    res = res.replace(/\x08egin/g, '\\begin');
    res = res.replace(/\x09an/g, '\\tan');
    res = res.replace(/\x09heta/g, '\\theta');
    res = res.replace(/\x09imes/g, '\\times');
    // \text{...} là lệnh hay dùng nhất nhưng lại thiếu ở đây: trong ngân hàng có câu
    // lưu thành "\" + TAB + "ext{ là số chẵn }", xuất ra Word thành công thức hỏng.
    res = res.replace(/\x09ext/g, '\\text');
    res = res.replace(/\x09frac/g, '\\tfrac');
    res = res.replace(/\x0Dightarrow/g, '\\rightarrow');
    res = res.replace(/\x0Dight/g, '\\right');
    res = res.replace(/\x0Dho/g, '\\rho');
    return res;
}

export function cleanObjectLatex(obj: any): any {
    if (typeof obj === 'string') return cleanLatexControlChars(obj);
    if (Array.isArray(obj)) return obj.map(cleanObjectLatex);
    if (obj !== null && typeof obj === 'object') {
        const newObj: any = {};
        for (const key in obj) newObj[key] = cleanObjectLatex(obj[key]);
        return newObj;
    }
    return obj;
}

/**
 * Bọc cặp $...$ cho chuỗi viết bằng LaTeX nhưng thiếu dấu $.
 *
 * Dùng cho ô "Đáp án đúng chính xác" của câu Trả lời ngắn: dữ liệu cũ lưu dạng
 * thô như "3\pi/8 + \sqrt{2}/4 + 6" nên KaTeX không nhận ra, hiển thị ra đúng
 * chuỗi ký tự thay vì công thức. Chuỗi đã có $ thì giữ nguyên; chuỗi thuần
 * số/chữ (ví dụ "12.5") cũng giữ nguyên để khỏi bị in nghiêng kiểu toán học.
 */
export function ensureMathDelimiters(raw: string | null | undefined): string {
  const s = String(raw ?? '').trim();
  if (!s) return '';
  if (s.includes('$')) return s;
  // Có lệnh LaTeX (\frac, \sqrt...) hoặc mũ/chỉ số thì mới cần bọc
  const coKyHieuToan = /\[a-zA-Z]+|[\^_]|\{|\}/.test(s);
  return coKyHieuToan ? `$${s}$` : s;
}
